// <auto-generated />
using System;
using Hospital_Management_System.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hospital_Management_System.Migrations
{
    [DbContext(typeof(HospitalDbContext))]
    [Migration("20260322155342_ThirdCreate")]
    partial class ThirdCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hospital_Management_System.Model.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2026, 3, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 1,
                            PatientId = 1,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2026, 3, 23, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 2,
                            PatientId = 2,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2026, 3, 24, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 3,
                            PatientId = 3,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2026, 3, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 4,
                            PatientId = 4,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2026, 3, 26, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 5,
                            PatientId = 5,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2026, 3, 27, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 6,
                            PatientId = 6,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 7,
                            PatientId = 7,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2026, 3, 29, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 8,
                            PatientId = 8,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2026, 3, 30, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 9,
                            PatientId = 9,
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2026, 3, 31, 0, 0, 0, 0, DateTimeKind.Local),
                            DoctorId = 10,
                            PatientId = 10,
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dr. Ahmed Hossam",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dr. Sara Khaled",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dr. Mohamed Adel",
                            Specialization = "Neurology"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Dr. Laila Samir",
                            Specialization = "Pediatrics"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Dr. Omar Fathy",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dr. Nour Hassan",
                            Specialization = "General Surgery"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Dr. Hana Tamer",
                            Specialization = "Gynecology"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Dr. Youssef Mahmoud",
                            Specialization = "Ophthalmology"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Dr. Mona Kamal",
                            Specialization = "ENT"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dr. Khaled Ali",
                            Specialization = "Psychiatry"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Ali",
                            Phone = "01012345678"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Sara Hassan",
                            Phone = "01023456789"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mohamed Tamer",
                            Phone = "01034567890"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Laila Fathy",
                            Phone = "01045678901"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Omar Mostafa",
                            Phone = "01056789012"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Nour El-Din",
                            Phone = "01067890123"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hana Mahmoud",
                            Phone = "01078901234"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Youssef Samir",
                            Phone = "01089012345"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Mona Kamal",
                            Phone = "01090123456"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Khaled Adel",
                            Phone = "01001234567"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 110,
                            AppointmentId = 1,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 2,
                            Amount = 120,
                            AppointmentId = 2,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 3,
                            Amount = 130,
                            AppointmentId = 3,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 4,
                            Amount = 140,
                            AppointmentId = 4,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 5,
                            Amount = 150,
                            AppointmentId = 5,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 6,
                            Amount = 160,
                            AppointmentId = 6,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 7,
                            Amount = 170,
                            AppointmentId = 7,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 8,
                            Amount = 180,
                            AppointmentId = 8,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 9,
                            Amount = 190,
                            AppointmentId = 9,
                            IsPaid = false
                        },
                        new
                        {
                            Id = 10,
                            Amount = 200,
                            AppointmentId = 10,
                            IsPaid = false
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Prescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<string>("Medications")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId")
                        .IsUnique();

                    b.ToTable("Prescriptions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentId = 1,
                            Medications = "Paracetamol 500mg",
                            Notes = "Patient has mild fever"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentId = 2,
                            Medications = "Cough Syrup",
                            Notes = "Patient has cough"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentId = 3,
                            Medications = "Ibuprofen",
                            Notes = "Patient has headache"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentId = 4,
                            Medications = "Vitamin C",
                            Notes = "Patient has flu"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentId = 5,
                            Medications = "Antihistamine",
                            Notes = "Patient has cold"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentId = 6,
                            Medications = "Muscle Relaxant",
                            Notes = "Patient has back pain"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentId = 7,
                            Medications = "Antacid",
                            Notes = "Patient has stomach ache"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentId = 8,
                            Medications = "Antihistamine",
                            Notes = "Patient has allergies"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentId = 9,
                            Medications = "Painkiller",
                            Notes = "Patient has migraine"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentId = 10,
                            Medications = "Antibiotic",
                            Notes = "Patient has infection"
                        });
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Appointment", b =>
                {
                    b.HasOne("Hospital_Management_System.Model.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hospital_Management_System.Model.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Payment", b =>
                {
                    b.HasOne("Hospital_Management_System.Model.Appointment", "Appointment")
                        .WithOne("Payment")
                        .HasForeignKey("Hospital_Management_System.Model.Payment", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Prescription", b =>
                {
                    b.HasOne("Hospital_Management_System.Model.Appointment", "Appointment")
                        .WithOne("Prescription")
                        .HasForeignKey("Hospital_Management_System.Model.Prescription", "AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Appointment", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Doctor", b =>
                {
                    b.Navigation("Appointments");
                });

            modelBuilder.Entity("Hospital_Management_System.Model.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
